# Generated by Django 2.2.1 on 2019-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uuid',
            field=models.CharField(default='abcd', max_length=50),
            preserve_default=False,
        ),
    ]
