# Generated by Django 2.2.1 on 2019-05-28 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
