# Generated by Django 2.2.1 on 2019-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20190528_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
